# included templates
include:
  # Node.js template
  - project: "to-be-continuous/node"
    ref: "3.12"
    file: "templates/gitlab-ci-node.yml"
  # Gitleaks template
  - project: "to-be-continuous/gitleaks"
    ref: "2.5"
    file: "templates/gitlab-ci-gitleaks.yml"
  # Renovate template
  - project: "to-be-continuous/renovate"
    ref: "1.2"
    file: "templates/gitlab-ci-renovate.yml"
  #GitLab Static Application Security Testing
  - template: Jobs/SAST.gitlab-ci.yml
  #Gitlab secret detection
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  #Gitlab code quality scanning
  - template: Jobs/Code-Quality.gitlab-ci.yml

# secret variables
# (define the variables below in your GitLab group/project variables)
# RENOVATE_TOKEN: A GitLab access token to allow Renovate crawl your projects. [See doc](https://docs.renovatebot.com/modules/platform/gitlab/#authentication)
# GITHUB_COM_TOKEN: A GitHub access token to allow Renovate fetch changelogs. [See doc](https://docs.renovatebot.com/getting-started/running/#githubcom-token-for-changelogs)

# your pipeline stages
stages:
  - build
  - test
  - package-build
  - package-test
  - infra
  - deploy
  - acceptance
  - publish
  - infra-prod
  - production

# enable code lint
variables:
  NODE_LINT_ENABLED: "true"

#run code quality check on merge request pipelines
code_quality:
  rules:
    - if: $CODE_QUALITY_DISABLED
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
  variables:
    TIMEOUT_SECONDS: 3600

#output code quality report as html and json
code_quality_html:
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]
