name: check project

on: [push]

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Super-Linter
        uses: super-linter/super-linter@v6.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build project
        run: npm build
