name: check project

on: [push]

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check formatting
        run: npm run lint

      - name: build project
        run: npm build
